# Site settings
title: AhLeung online
description: Sharing somethings online
url: "http://ahlearn.github.io"
twitter_username: ahlearn
github_username: ahlearn

# Build settings
markdown_ext: md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]